shoonyatech/wallora.com

.github/ISSUE_TEMPLATE/issue.md
=> feat(issue.md) : create an issue template

package-lock.json, package.json, pages/_app.tsx, pages/index.tsx, postcss.config.js, tailwind.config.js
=> feat(Style): add tailwind support to the app

.env.local.sample, package-lock.json, package.json, pages/_app.tsx, pages/api/auth/[...auth0].tsx, pages/index.tsx
Fixes #12 
Fixes #13 
Fixes #14 
Fixes #15 
Referred documentation : https://auth0.com/docs/quickstart/webapp/nextjs.
Enabled Signup and SignIn using Auth0 in project. 
This PR creates the following routes:
- api/auth/login: The route used to perform login with Auth0.
- /api/auth/logout: The route used to log the user out.
- /api/auth/callback: The route Auth0 will redirect the user to after a successful login. (**at present no actual callback in project**)
- /api/auth/me: The route to fetch the user profile from.
Tested password reset and verification email as well.
All these are via Auth0.
cc: @souvikbasu
=> feat(auth): integrate Auth0 signup/in using email/password

tailwind.config.js
Fixes #18 
Add config to purge unused style statements from Tailwind
=> feat(style): configure tailwind to prune

package-lock.json, pages/index.tsx
Fixes: #35 
Logout scenario missed to follow styling, hence fixing in this PR.
=> bug(ui): wrap logout scenario in styling

.env.local.sample, components/Header.tsx, pages/index.tsx
Fixes #38 
Description:
Create Header component and move the Sign in button to top right of the Header.
=> feat(Home): create Header component and add Sign in link

.eslintignore, .eslintrc.js, .prettierignore, .prettierrc.js, package-lock.json, package.json, pages/_app.tsx
=> build(app): configure eslint prettier and husky

.env.local.sample, README.md, lib/ga/index.js, pages/_app.tsx, pages/_document.tsx
Fixes #20 
- Added GA support
- Updated README.md to give instructions on how to use GA and Auth0 with references
=> feat(seo): add ga support

components/Footer.tsx, components/Header/index.tsx, pages/_app.tsx, pages/index.tsx, styles/global.css, tailwind.config.js
=> feat(style): add theming support

.storybook/preview.js
=> feat(style): enable tailwind classes for storybook

components/Footer/Footer.stories.tsx, components/Footer/index.tsx, package.json, pages/index.tsx, pages/privacy.tsx, pages/terms.tsx
=> feat(footer): add terms and privacy links

components/Feedback/Feedback.stories.tsx, components/Feedback/index.tsx, components/FeedbackPanel/FeedbackPanel.stories.tsx, components/FeedbackPanel/index.tsx, next.config.js, package-lock.json, package.json, pages/index.tsx, styles/material.ui.theme.provider.tsx, tailwind.config.js
Fixes: #56 
Old version without material-ui
Latest version with material-ui
=> feat(home): create feedback panel

.github/pull_request_template.md
=> feat(template) : create default template for pr

components/Header/index.tsx
=>  fix(style): updated header height and login texts

.eslintrc.json, apis/apollo.client.tsx, components/Feedback/index.tsx, components/FeedbackPanel/index.tsx, package-lock.json, package.json, pages/_app.tsx, tailwind.config.js
This PR fixes issue: #88 
Description of the change: 
- Added apollo client and used it in feedbcak panel
- Removed custom styling from tailwind.config
=> feat(feedback-panel): make backend call using Apollo client

README.md, package-lock.json, package.json
=> build(devex): add commitzen tool to enforce commit message format

components/finance/FinanceDateHeader/FinanceDateHeader.stories.tsx, components/finance/FinanceDateHeader/index.tsx, lib/date-helper.tsx, package-lock.json, pages/_app.tsx, pages/finance.tsx
fix #111
This PR Fixes : #111 
=> feat(finance): add nav buttons

components/finance/FinanceDateHeader/FinanceDateHeader.stories.tsx, pages/_app.tsx
=> fix(story-book): fixed import

components/finance/FinanceCategories/index.tsx, components/finance/FinanceCategoryListItem/index.tsx, pages/finance.tsx, tailwind.config.js
Fixes #89
Note :  The nav bar is purposely made to be hidden using dev tools as some part of the component gets hidden under It.
=> feat(finance): create list of income/expense categories

components/common/BaseLayout/index.tsx, pages/dashboard.tsx, pages/index.tsx
user will be redirected to login if he/she tries to navigate to protected pages
=> feat(_app.tsx) : add route guard to protected url's

components/finance/FinanceCategories/index.tsx, components/finance/FinanceCategoryListItem/index.tsx, components/finance/FinancePanel/index.tsx, components/finance/FinanceSpreadSheet/index.tsx, pages/finance.tsx
partial fix of #104 
Screenshot: (if applicable):   
the spreadsheet is made using flex as the flow of document structure is correct .
Instead of Having the all list categories first then grid ,
I have added the a list Item and Its cell followed by others.
=> Spreadsheet

src/mocks/handlers.tsx
=> feat(msw): mock graphql calls

components/common/BaseLayout/index.tsx, components/finance/FinanceCategories/index.tsx, components/finance/FinanceDateHeader/index.tsx, components/finance/FinanceSpreadSheet/index.tsx, pages/finance.tsx, tailwind.config.js
=> refactor(finance): align dateheaders with spreadsheet cells

components/common/SideBar/index.tsx, components/finance/ExpensePanelDetails/index.tsx, components/finance/ExpensePanelRows/index.tsx, components/finance/FinanceCategories/index.tsx, components/finance/FinanceCategoryList/index.tsx, components/finance/FinanceCategoryListItem/index.tsx, components/finance/FinanceDateHeader/index.tsx, components/finance/FinanceSpreadSheet/index.tsx, package-lock.json, package.json, pages/finance.tsx
Fixes #104 
Screenshot: (if applicable):
=> place finance panel right the below the clicked cell

components/finance/IncomeExpenseBrick/index.tsx, pages/finance.tsx, src/mocks/handlers.tsx
=> feat(finance): integrating with currencies api

components/common/SideBar/index.tsx, components/common/TabsMobileMode/index.tsx
=> Set icons in Sidebar

components/common/BaseLayout/index.tsx, components/home/MainContent/index.tsx
Fixes #148
Screenshot: (if applicable):
=> fix(main): show content which used to be hidden under unexpanded nav bar

components/common/BaseLayout/index.tsx, components/common/Header/index.tsx, components/common/SideBar/index.tsx, components/finance/ExpensePanelDetails/index.tsx, components/finance/ExpensePanelRows/index.tsx, components/finance/FinanceCategories/index.tsx, components/finance/FinanceSpreadSheet/index.tsx, components/finance/IncomeExpenseBrick/index.tsx, pages/finance/actuals.tsx
=> Fix: bunch of code cleanups in finance actual page

README.md
Fixes # NA
Description of the change: Updated contributors name (self) in README.md
First PR
=> doc(README): add Rajakvk as a contributor

components/common/Footer/index.tsx
Fixes # Not Applicable
Screenshot: NA
Description of the change: Add contribute link at footer. Point link to [shoonyatech/wallora](https://github.com/shoonyatech/wallora.com)
=> doc(home): Add contribute link at footer

README.md
Screenshot: (if applicable):  no
Description of the change: Add Kratika as contributer
=> doc(Readme) : add Kratika as contributor

README.md
doc(README): add KartheeK as a contributor
=> doc(README): add KartheeK as a contributor

README.md, package-lock.json
=> docs: add Shubham as a contributor

README.md
Description of the change: Add graphql setup information in README.md
=> docs: add graphql setup information

README.md
=> docs(readme): add shriramcs as a contributor

README.md
=> docs: doc(README.md): add Contributor Kevin

README.md, components/finance/FinanceCategories/index.tsx, components/finance/FinanceDateHeader/index.tsx, src/mocks/handlers.tsx
=> Finance: show total expense of a day

components/finance/FinanceCategories/index.tsx, components/finance/FinanceDateHeader/index.tsx
=> Finance: show total expense of a day 

components/dashboard/CurrentWorthChart/CurrentWorthChart.stories.tsx, components/dashboard/CurrentWorthChart/index.tsx, pages/dashboard.tsx
Description of the change: display current worth chart
=> feat(dashboard): display current worth chart

components/dashboard/CurrentWorthChart/index.tsx
Description of the change: add owe chart
=> feat(dashboard): add owe chart

components/common/ControlButtons/index.tsx, components/finance/FinanceMonthHeader/FinanceMonthHeader.stories.tsx, components/finance/FinanceMonthHeader/index.tsx, lib/date-helper.tsx, pages/finance/plan.tsx
Description of the change: add month header
=> feat(plan): add month header

components/dashboard/CurrentWorthChart/index.tsx, components/finance/FinanceMonthHeader/index.tsx, lib/date-helper.tsx, pages/finance/plan.tsx
Description of the change: integrating with charts api
=> feat(dashboard): integrating with charts api

components/finance/FinanceMonthHeader/index.tsx, components/finance/PlanSidebar/index.tsx, components/finance/PlanSpreadSheet/index.tsx, pages/finance/plan.tsx
Description of the change: add monthly data
=> feat(plan): add monthly data
